name: deployment

on:
  pull_request:
    types: 
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v1

    - name: get list of files in PR
      if: github.event.pull_request
      run: |
        URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/files"
          FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename')
          echo $FILES
